name: CI

on:
  push:
  pull_request:
    branches: [ $default-branch ]
  release:
    types:
      - created

jobs:
  test:
    name: "Erlang Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [25, 26]
      fail-fast: false
    container:
      image: erlang:${{ matrix.otp }}
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: rebar3 eunit